"""Structural storage contracts for repo-level provider parity."""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Protocol

from pydantic import BaseModel

NotificationType = Literal["steer", "command", "agent"]


# ---------------------------------------------------------------------------
# Contact System — row types + enums
# ---------------------------------------------------------------------------


class MemberType(str, Enum):
    MYCEL_AGENT = "mycel_agent"
    OPENCLAW_AGENT = "openclaw_agent"
    HUMAN = "human"


class MemberRow(BaseModel):
    id: str
    name: str
    type: MemberType
    avatar: str | None = None
    description: str | None = None
    config_dir: str | None = None
    owner_id: str | None = None  # human member_id for agents, NULL for humans
    created_at: float
    updated_at: float | None = None


class AccountRow(BaseModel):
    id: str
    member_id: str
    username: str
    password_hash: str | None = None
    api_key_hash: str | None = None
    created_at: float


class ContactRow(BaseModel):
    id: str
    owner_id: str
    contact_id: str
    created_at: float


class ConversationRow(BaseModel):
    id: str
    title: str | None = None
    status: str = "active"
    created_at: float
    updated_at: float | None = None


class ConversationMemberRow(BaseModel):
    conversation_id: str
    member_id: str
    joined_at: float
    last_read_at: float | None = None


class ConversationMessageRow(BaseModel):
    id: str
    conversation_id: str
    sender_id: str
    content: str
    created_at: float


# ---------------------------------------------------------------------------
# Contact System — repo protocols
# ---------------------------------------------------------------------------


class MemberRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: MemberRow) -> None: ...
    def get_by_id(self, member_id: str) -> MemberRow | None: ...
    def get_by_name(self, name: str) -> MemberRow | None: ...
    def list_all(self) -> list[MemberRow]: ...
    def list_by_owner(self, owner_id: str) -> list[MemberRow]: ...
    def update(self, member_id: str, **fields: Any) -> None: ...
    def delete(self, member_id: str) -> None: ...


class AccountRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: AccountRow) -> None: ...
    def get_by_id(self, account_id: str) -> AccountRow | None: ...
    def get_by_member_id(self, member_id: str) -> AccountRow | None: ...
    def get_by_username(self, username: str) -> AccountRow | None: ...
    def delete(self, account_id: str) -> None: ...


class ContactRepo(Protocol):
    def close(self) -> None: ...
    def create_pair(self, owner_a: str, owner_b: str, created_at: float) -> None: ...
    def list_by_owner(self, owner_id: str) -> list[ContactRow]: ...
    def exists(self, owner_id: str, contact_id: str) -> bool: ...
    def delete_pair(self, owner_a: str, owner_b: str) -> None: ...


class ConversationRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: ConversationRow) -> None: ...
    def get_by_id(self, conversation_id: str) -> ConversationRow | None: ...
    def list_by_member(self, member_id: str) -> list[ConversationRow]: ...
    def update_status(self, conversation_id: str, status: str) -> None: ...


class ConversationMemberRepo(Protocol):
    def close(self) -> None: ...
    def add_member(self, conversation_id: str, member_id: str, joined_at: float) -> None: ...
    def remove_member(self, conversation_id: str, member_id: str) -> None: ...
    def list_members(self, conversation_id: str) -> list[ConversationMemberRow]: ...
    def list_conversations_for_member(self, member_id: str) -> list[str]: ...
    def is_member(self, conversation_id: str, member_id: str) -> bool: ...
    def update_last_read(self, conversation_id: str, member_id: str, last_read_at: float) -> None: ...
    def get_last_read_at(self, conversation_id: str, member_id: str) -> float | None: ...
    def list_all_edges(self) -> list[tuple[str, str, int]]: ...


class ConversationMessageRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: ConversationMessageRow) -> None: ...
    def list_by_conversation(self, conversation_id: str, *, limit: int = 50, before: float | None = None) -> list[ConversationMessageRow]: ...
    def count_unread(self, conversation_id: str, member_id: str) -> int: ...
    def search_in_conversation(self, conversation_id: str, query: str, *, limit: int = 50) -> list[ConversationMessageRow]: ...


class CheckpointRepo(Protocol):
    def close(self) -> None: ...
    def list_thread_ids(self) -> list[str]: ...
    def delete_thread_data(self, thread_id: str) -> None: ...
    def delete_checkpoints_by_ids(self, thread_id: str, checkpoint_ids: list[str]) -> None: ...


class ThreadConfigRepo(Protocol):
    def close(self) -> None: ...
    def save_metadata(self, thread_id: str, sandbox_type: str, cwd: str | None) -> None: ...
    def save_model(self, thread_id: str, model: str) -> None: ...
    def update_fields(self, thread_id: str, **fields: str | None) -> None: ...
    def lookup_model(self, thread_id: str) -> str | None: ...
    def lookup_config(self, thread_id: str) -> dict[str, str | None] | None: ...
    def lookup_metadata(self, thread_id: str) -> tuple[str, str | None] | None: ...
    def delete_thread_config(self, thread_id: str) -> None: ...


class RunEventRepo(Protocol):
    def close(self) -> None: ...
    def append_event(
        self,
        thread_id: str,
        run_id: str,
        event_type: str,
        data: dict[str, Any],
        message_id: str | None = None,
    ) -> int: ...
    def list_events(
        self,
        thread_id: str,
        run_id: str,
        *,
        after: int = 0,
        limit: int = 200,
    ) -> list[dict[str, Any]]: ...
    def latest_seq(self, thread_id: str) -> int: ...
    def latest_run_id(self, thread_id: str) -> str | None: ...
    def list_run_ids(self, thread_id: str) -> list[str]: ...
    def run_start_seq(self, thread_id: str, run_id: str) -> int: ...
    def delete_runs(self, thread_id: str, run_ids: list[str]) -> int: ...
    def delete_thread_events(self, thread_id: str) -> int: ...


class FileOperationRepo(Protocol):
    def close(self) -> None: ...
    def record(
        self,
        thread_id: str,
        checkpoint_id: str,
        operation_type: str,
        file_path: str,
        before_content: str | None,
        after_content: str,
        changes: list[dict] | None = None,
    ) -> str: ...
    def get_operations_for_thread(self, thread_id: str, status: str = "applied") -> list[Any]: ...
    def get_operations_after_checkpoint(self, thread_id: str, checkpoint_id: str) -> list[Any]: ...
    def get_operations_between_checkpoints(
        self,
        thread_id: str,
        from_checkpoint_id: str,
        to_checkpoint_id: str,
    ) -> list[Any]: ...
    def get_operations_for_checkpoint(self, thread_id: str, checkpoint_id: str) -> list[Any]: ...
    def count_operations_for_checkpoint(self, thread_id: str, checkpoint_id: str) -> int: ...
    def mark_reverted(self, operation_ids: list[str]) -> None: ...
    def delete_thread_operations(self, thread_id: str) -> int: ...


# @@@summary-row-contract - standardize summary row payload as dict to keep provider parity explicit for static type checks.
type SummaryRow = dict[str, Any]


class SummaryRepo(Protocol):
    def ensure_tables(self) -> None: ...
    def save_summary(
        self,
        summary_id: str,
        thread_id: str,
        summary_text: str,
        compact_up_to_index: int,
        compacted_at: int,
        is_split_turn: bool,
        split_turn_prefix: str | None,
        created_at: str,
    ) -> None: ...
    def get_latest_summary_row(self, thread_id: str) -> SummaryRow | None: ...
    def list_summaries(self, thread_id: str) -> list[dict[str, object]]: ...
    def delete_thread_summaries(self, thread_id: str) -> None: ...
    def close(self) -> None: ...


class QueueItem(BaseModel):
    """A dequeued message with its notification type."""
    content: str
    notification_type: NotificationType


class QueueRepo(Protocol):
    def close(self) -> None: ...
    def enqueue(self, thread_id: str, content: str, notification_type: NotificationType = "steer") -> None: ...
    def dequeue(self, thread_id: str) -> QueueItem | None: ...
    def drain_all(self, thread_id: str) -> list[QueueItem]: ...
    def peek(self, thread_id: str) -> bool: ...
    def list_queue(self, thread_id: str) -> list[dict[str, Any]]: ...
    def clear_queue(self, thread_id: str) -> None: ...
    def count(self, thread_id: str) -> int: ...


class EvalRepo(Protocol):
    def ensure_schema(self) -> None: ...
    def save_trajectory(self, trajectory: Any, trajectory_json: str) -> str: ...
    def save_metrics(self, run_id: str, tier: str, timestamp: str, metrics_json: str) -> None: ...
    def get_trajectory_json(self, run_id: str) -> str | None: ...
    def list_runs(self, thread_id: str | None = None, limit: int = 50) -> list[dict]: ...
    def get_metrics(self, run_id: str, tier: str | None = None) -> list[dict]: ...
