"""Structural storage contracts for repo-level provider parity."""

from __future__ import annotations

from typing import Any, Protocol


class CheckpointRepo(Protocol):
    def close(self) -> None: ...
    def list_thread_ids(self) -> list[str]: ...
    def delete_thread_data(self, thread_id: str) -> None: ...
    def delete_checkpoints_by_ids(self, thread_id: str, checkpoint_ids: list[str]) -> None: ...


class ThreadConfigRepo(Protocol):
    def close(self) -> None: ...
    def save_metadata(self, thread_id: str, sandbox_type: str, cwd: str | None) -> None: ...
    def save_model(self, thread_id: str, model: str) -> None: ...
    def update_fields(self, thread_id: str, **fields: str | None) -> None: ...
    def lookup_model(self, thread_id: str) -> str | None: ...
    def lookup_config(self, thread_id: str) -> dict[str, str | None] | None: ...
    def lookup_metadata(self, thread_id: str) -> tuple[str, str | None] | None: ...
    def delete_thread_config(self, thread_id: str) -> None: ...


class RunEventRepo(Protocol):
    def close(self) -> None: ...
    def append_event(
        self,
        thread_id: str,
        run_id: str,
        event_type: str,
        data: dict[str, Any],
        message_id: str | None = None,
    ) -> int: ...
    def list_events(
        self,
        thread_id: str,
        run_id: str,
        *,
        after: int = 0,
        limit: int = 200,
    ) -> list[dict[str, Any]]: ...
    def latest_seq(self, thread_id: str) -> int: ...
    def latest_run_id(self, thread_id: str) -> str | None: ...
    def list_run_ids(self, thread_id: str) -> list[str]: ...
    def delete_runs(self, thread_id: str, run_ids: list[str]) -> int: ...
    def delete_thread_events(self, thread_id: str) -> int: ...


class FileOperationRepo(Protocol):
    def close(self) -> None: ...
    def record(
        self,
        thread_id: str,
        checkpoint_id: str,
        operation_type: str,
        file_path: str,
        before_content: str | None,
        after_content: str,
        changes: list[dict] | None = None,
    ) -> str: ...
    def get_operations_for_thread(self, thread_id: str, status: str = "applied") -> list[Any]: ...
    def get_operations_after_checkpoint(self, thread_id: str, checkpoint_id: str) -> list[Any]: ...
    def get_operations_between_checkpoints(
        self,
        thread_id: str,
        from_checkpoint_id: str,
        to_checkpoint_id: str,
    ) -> list[Any]: ...
    def get_operations_for_checkpoint(self, thread_id: str, checkpoint_id: str) -> list[Any]: ...
    def count_operations_for_checkpoint(self, thread_id: str, checkpoint_id: str) -> int: ...
    def mark_reverted(self, operation_ids: list[str]) -> None: ...
    def delete_thread_operations(self, thread_id: str) -> int: ...


# @@@summary-row-contract - standardize summary row payload as dict to keep provider parity explicit for static type checks.
type SummaryRow = dict[str, Any]


class SummaryRepo(Protocol):
    def ensure_tables(self) -> None: ...
    def save_summary(
        self,
        summary_id: str,
        thread_id: str,
        summary_text: str,
        compact_up_to_index: int,
        compacted_at: int,
        is_split_turn: bool,
        split_turn_prefix: str | None,
        created_at: str,
    ) -> None: ...
    def get_latest_summary_row(self, thread_id: str) -> SummaryRow | None: ...
    def list_summaries(self, thread_id: str) -> list[dict[str, object]]: ...
    def delete_thread_summaries(self, thread_id: str) -> None: ...
    def close(self) -> None: ...


class EvalRepo(Protocol):
    def ensure_schema(self) -> None: ...
    def save_trajectory(self, trajectory: Any, trajectory_json: str) -> str: ...
    def save_metrics(self, run_id: str, tier: str, timestamp: str, metrics_json: str) -> None: ...
    def get_trajectory_json(self, run_id: str) -> str | None: ...
    def list_runs(self, thread_id: str | None = None, limit: int = 50) -> list[dict]: ...
    def get_metrics(self, run_id: str, tier: str | None = None) -> list[dict]: ...
