"""Structural storage contracts for repo-level provider parity."""

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Protocol

from pydantic import BaseModel

NotificationType = Literal["steer", "command", "agent", "chat"]


# ---------------------------------------------------------------------------
# Entity-Chat — enums + row types
# ---------------------------------------------------------------------------


class MemberType(str, Enum):
    HUMAN = "human"
    MYCEL_AGENT = "mycel_agent"
    OPENCLAW_AGENT = "openclaw_agent"


class MemberRow(BaseModel):
    id: str
    name: str
    type: MemberType
    avatar: str | None = None
    description: str | None = None
    config_dir: str | None = None
    owner_id: str | None = None
    next_entity_seq: int = 0
    created_at: float
    updated_at: float | None = None


class AccountRow(BaseModel):
    id: str
    member_id: str
    username: str
    password_hash: str | None = None
    api_key_hash: str | None = None
    created_at: float


class EntityRow(BaseModel):
    id: str
    type: str  # 'human' | 'agent'
    member_id: str
    name: str
    avatar: str | None = None
    thread_id: str | None = None
    created_at: float


class ChatRow(BaseModel):
    id: str
    title: str | None = None
    status: str = "active"
    created_at: float
    updated_at: float | None = None


class ChatEntityRow(BaseModel):
    chat_id: str
    entity_id: str
    joined_at: float
    last_read_at: float | None = None
    muted: bool = False
    mute_until: float | None = None  # None = permanent mute when muted=True


class ChatMessageRow(BaseModel):
    id: str
    chat_id: str
    sender_entity_id: str
    content: str
    mentioned_entity_ids: list[str] = []
    created_at: float


# ---------------------------------------------------------------------------
# Delivery strategy — contact relationships + delivery actions
# ---------------------------------------------------------------------------


class DeliveryAction(str, Enum):
    """What to do when a chat message reaches a recipient."""
    DELIVER = "deliver"  # full delivery: inject into agent context, wake agent
    NOTIFY = "notify"    # red dot only: message stored, unread counted, no delivery
    DROP = "drop"        # silent: message stored but invisible to this entity


ContactRelation = Literal["normal", "blocked", "muted"]


class ContactRow(BaseModel):
    """Directional relationship between two entities. A→B independent of B→A."""
    owner_entity_id: str
    target_entity_id: str
    relation: ContactRelation
    created_at: float
    updated_at: float | None = None


class CheckpointRepo(Protocol):
    def close(self) -> None: ...
    def list_thread_ids(self) -> list[str]: ...
    def delete_thread_data(self, thread_id: str) -> None: ...
    def delete_checkpoints_by_ids(self, thread_id: str, checkpoint_ids: list[str]) -> None: ...


class RunEventRepo(Protocol):
    def close(self) -> None: ...
    def append_event(
        self,
        thread_id: str,
        run_id: str,
        event_type: str,
        data: dict[str, Any],
        message_id: str | None = None,
    ) -> int: ...
    def list_events(
        self,
        thread_id: str,
        run_id: str,
        *,
        after: int = 0,
        limit: int = 200,
    ) -> list[dict[str, Any]]: ...
    def latest_seq(self, thread_id: str) -> int: ...
    def latest_run_id(self, thread_id: str) -> str | None: ...
    def list_run_ids(self, thread_id: str) -> list[str]: ...
    def run_start_seq(self, thread_id: str, run_id: str) -> int: ...
    def delete_runs(self, thread_id: str, run_ids: list[str]) -> int: ...
    def delete_thread_events(self, thread_id: str) -> int: ...


class FileOperationRepo(Protocol):
    def close(self) -> None: ...
    def record(
        self,
        thread_id: str,
        checkpoint_id: str,
        operation_type: str,
        file_path: str,
        before_content: str | None,
        after_content: str,
        changes: list[dict] | None = None,
    ) -> str: ...
    def get_operations_for_thread(self, thread_id: str, status: str = "applied") -> list[Any]: ...
    def get_operations_after_checkpoint(self, thread_id: str, checkpoint_id: str) -> list[Any]: ...
    def get_operations_between_checkpoints(
        self,
        thread_id: str,
        from_checkpoint_id: str,
        to_checkpoint_id: str,
    ) -> list[Any]: ...
    def get_operations_for_checkpoint(self, thread_id: str, checkpoint_id: str) -> list[Any]: ...
    def count_operations_for_checkpoint(self, thread_id: str, checkpoint_id: str) -> int: ...
    def mark_reverted(self, operation_ids: list[str]) -> None: ...
    def delete_thread_operations(self, thread_id: str) -> int: ...


# @@@summary-row-contract - standardize summary row payload as dict to keep provider parity explicit for static type checks.
type SummaryRow = dict[str, Any]


class SummaryRepo(Protocol):
    def ensure_tables(self) -> None: ...
    def save_summary(
        self,
        summary_id: str,
        thread_id: str,
        summary_text: str,
        compact_up_to_index: int,
        compacted_at: int,
        is_split_turn: bool,
        split_turn_prefix: str | None,
        created_at: str,
    ) -> None: ...
    def get_latest_summary_row(self, thread_id: str) -> SummaryRow | None: ...
    def list_summaries(self, thread_id: str) -> list[dict[str, object]]: ...
    def delete_thread_summaries(self, thread_id: str) -> None: ...
    def close(self) -> None: ...


class QueueItem(BaseModel):
    """A dequeued message with its notification type."""
    content: str
    notification_type: NotificationType
    source: str | None = None          # "owner" | "external" | "system"
    sender_entity_id: str | None = None
    sender_name: str | None = None
    sender_avatar_url: str | None = None
    is_steer: bool = False


class QueueRepo(Protocol):
    def close(self) -> None: ...
    def enqueue(self, thread_id: str, content: str, notification_type: NotificationType = "steer",
                source: str | None = None, sender_entity_id: str | None = None,
                sender_name: str | None = None) -> None: ...
    def dequeue(self, thread_id: str) -> QueueItem | None: ...
    def drain_all(self, thread_id: str) -> list[QueueItem]: ...
    def peek(self, thread_id: str) -> bool: ...
    def list_queue(self, thread_id: str) -> list[dict[str, Any]]: ...
    def clear_queue(self, thread_id: str) -> None: ...
    def count(self, thread_id: str) -> int: ...


class WorkspaceRepo(Protocol):
    def close(self) -> None: ...
    def create(self, workspace_id: str, host_path: str, name: str | None, created_at: str) -> None: ...
    def get(self, workspace_id: str) -> dict[str, Any] | None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def delete(self, workspace_id: str) -> bool: ...


class WorkplaceRepo(Protocol):
    """Agent-level persistent workplace storage. Keyed by (member_id, provider_type)."""
    def close(self) -> None: ...
    def upsert(self, member_id: str, provider_type: str,
               backend_ref: str, mount_path: str, created_at: str) -> None: ...
    def get(self, member_id: str, provider_type: str) -> dict[str, Any] | None: ...
    def list_by_member(self, member_id: str) -> list[dict[str, Any]]: ...
    def delete(self, member_id: str, provider_type: str) -> bool: ...
    def delete_all_for_member(self, member_id: str) -> int: ...


class EvalRepo(Protocol):
    def ensure_schema(self) -> None: ...
    def save_trajectory(self, trajectory: Any, trajectory_json: str) -> str: ...
    def save_metrics(self, run_id: str, tier: str, timestamp: str, metrics_json: str) -> None: ...
    def get_trajectory_json(self, run_id: str) -> str | None: ...
    def list_runs(self, thread_id: str | None = None, limit: int = 50) -> list[dict]: ...
    def get_metrics(self, run_id: str, tier: str | None = None) -> list[dict]: ...


# ---------------------------------------------------------------------------
# Entity-Chat — repo protocols
# ---------------------------------------------------------------------------


class MemberRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: MemberRow) -> None: ...
    def get_by_id(self, member_id: str) -> MemberRow | None: ...
    def get_by_name(self, name: str) -> MemberRow | None: ...
    def list_all(self) -> list[MemberRow]: ...
    def list_by_owner(self, owner_id: str) -> list[MemberRow]: ...
    def update(self, member_id: str, **fields: Any) -> None: ...
    def increment_entity_seq(self, member_id: str) -> int: ...
    def delete(self, member_id: str) -> None: ...


class AccountRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: AccountRow) -> None: ...
    def get_by_id(self, account_id: str) -> AccountRow | None: ...
    def get_by_member_id(self, member_id: str) -> AccountRow | None: ...
    def get_by_username(self, username: str) -> AccountRow | None: ...
    def delete(self, account_id: str) -> None: ...


class EntityRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: EntityRow) -> None: ...
    def get_by_id(self, entity_id: str) -> EntityRow | None: ...
    def get_by_member_id(self, member_id: str) -> list[EntityRow]: ...
    def get_by_thread_id(self, thread_id: str) -> EntityRow | None: ...
    def list_all(self) -> list[EntityRow]: ...
    def list_by_type(self, entity_type: str) -> list[EntityRow]: ...
    def delete(self, entity_id: str) -> None: ...


class ChatRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: ChatRow) -> None: ...
    def get_by_id(self, chat_id: str) -> ChatRow | None: ...
    def delete(self, chat_id: str) -> None: ...


class ChatEntityRepo(Protocol):
    def close(self) -> None: ...
    def add_entity(self, chat_id: str, entity_id: str, joined_at: float) -> None: ...
    def list_entities(self, chat_id: str) -> list[ChatEntityRow]: ...
    def list_chats_for_entity(self, entity_id: str) -> list[str]: ...
    def is_entity_in_chat(self, chat_id: str, entity_id: str) -> bool: ...
    def update_last_read(self, chat_id: str, entity_id: str, last_read_at: float) -> None: ...
    def update_mute(self, chat_id: str, entity_id: str, muted: bool, mute_until: float | None = None) -> None: ...
    def find_chat_between(self, entity_a: str, entity_b: str) -> str | None: ...


class ChatMessageRepo(Protocol):
    def close(self) -> None: ...
    def create(self, row: ChatMessageRow) -> None: ...
    def list_by_chat(self, chat_id: str, *, limit: int = 50, before: float | None = None) -> list[ChatMessageRow]: ...
    def list_unread(self, chat_id: str, entity_id: str) -> list[ChatMessageRow]: ...
    def count_unread(self, chat_id: str, entity_id: str) -> int: ...
    def list_by_time_range(self, chat_id: str, *, after: float | None = None, before: float | None = None, limit: int = 100) -> list[ChatMessageRow]: ...
    def search(self, query: str, *, chat_id: str | None = None, limit: int = 50) -> list[ChatMessageRow]: ...


class ThreadRepo(Protocol):
    def close(self) -> None: ...
    def create(self, thread_id: str, member_id: str, sandbox_type: str,
               cwd: str | None, created_at: float, **extra: Any) -> None: ...
    def get_by_id(self, thread_id: str) -> dict[str, Any] | None: ...
    def list_by_member(self, member_id: str) -> list[dict[str, Any]]: ...
    def list_by_owner(self, owner_member_id: str) -> list[dict[str, Any]]: ...
    def update(self, thread_id: str, **fields: Any) -> None: ...
    def delete(self, thread_id: str) -> None: ...


class ContactRepo(Protocol):
    def close(self) -> None: ...
    def upsert(self, row: ContactRow) -> None: ...
    def get(self, owner_entity_id: str, target_entity_id: str) -> ContactRow | None: ...
    def list_for_entity(self, owner_entity_id: str) -> list[ContactRow]: ...
    def delete(self, owner_entity_id: str, target_entity_id: str) -> None: ...


class DeliveryResolver(Protocol):
    """Evaluates delivery strategy for a chat message recipient.

    Checks contact-level block/mute, then chat-level mute, then defaults to DELIVER.
    """
    def resolve(self, recipient_entity_id: str, chat_id: str, sender_entity_id: str, *, is_mentioned: bool = False) -> DeliveryAction: ...
