agent:
  model: "claude-sonnet-4-5-20250929"
  workspace_root: null
  read_only: false
  enable_audit_log: true

system_prompt: null

tools:
  read_file: true
  write_file: true
  edit_file: true
  multi_edit: true
  list_dir: true
  grep_search: true
  find_by_name: true
  web_search: true
  read_url_content: true
  view_web_content: true
  run_command: true
  command_status: true

  filesystem_read_only: false
  filesystem_allowed_extensions: null
  command_block_dangerous: true
  command_block_network: false
