agent:
  model: "claude-sonnet-4-5-20250929"
  workspace_root: null

system_prompt: null

tool:
  filesystem:
    enabled: true
    tools:
      read_file:
        enabled: true
        max_file_size: 10485760  # 10MB in bytes
      write_file: true
      edit_file: true
      multi_edit: true
      list_dir: true

  search:
    enabled: true
    max_results: 50
    tools:
      grep_search:
        enabled: true
        max_file_size: 10485760  # 10MB in bytes
      find_by_name: true

  web:
    enabled: true
    timeout: 15
    tools:
      web_search:
        enabled: true
        max_results: 5
        tavily_api_key: null  # fallback to TAVILY_API_KEY env var
        exa_api_key: null     # fallback to EXA_API_KEY env var
        firecrawl_api_key: null  # fallback to FIRECRAWL_API_KEY env var
      read_url_content:
        enabled: true
        jina_api_key: null    # fallback to JINA_AI_API_KEY env var
      view_web_content: true

  command:
    enabled: true
    tools:
      run_command:
        enabled: true
        default_timeout: 120
      command_status: true

mcp:
  enabled: false
  servers: {}
