agent:
  model: "claude-sonnet-4-5-20250929"
  workspace_root: null
  read_only: false
  enable_audit_log: true

system_prompt: null

tools:
  filesystem:
    enabled: true
    read_only: false
    allowed_extensions: null
    read_file: true
    write_file: true
    edit_file: true
    multi_edit: true
    list_dir: true

  search:
    enabled: true
    grep_search: true
    find_by_name: true

  web:
    enabled: true
    web_search: true
    read_url_content: true
    view_web_content: true

  command:
    enabled: true
    block_dangerous_commands: true
    block_network_commands: false
    run_command: true
    command_status: true

mcp:
  enabled: false
  servers: {}

skills:
  enabled: false
