export const TOOL_BADGE_STYLES: Record<string, { bg: string; text: string; label: string }> = {
  Bash: { bg: "bg-blue-50", text: "text-blue-600", label: "Bash" },
  run_command: { bg: "bg-blue-50", text: "text-blue-600", label: "Bash" },
  execute_command: { bg: "bg-blue-50", text: "text-blue-600", label: "Bash" },
  Read: { bg: "bg-emerald-50", text: "text-emerald-600", label: "Read" },
  read_file: { bg: "bg-emerald-50", text: "text-emerald-600", label: "Read" },
  Edit: { bg: "bg-amber-50", text: "text-amber-600", label: "Edit" },
  edit_file: { bg: "bg-amber-50", text: "text-amber-600", label: "Edit" },
  Write: { bg: "bg-amber-50", text: "text-amber-600", label: "Write" },
  write_file: { bg: "bg-amber-50", text: "text-amber-600", label: "Write" },
  Grep: { bg: "bg-purple-50", text: "text-purple-600", label: "Grep" },
  Glob: { bg: "bg-purple-50", text: "text-purple-600", label: "Glob" },
  search: { bg: "bg-purple-50", text: "text-purple-600", label: "Search" },
  find_files: { bg: "bg-purple-50", text: "text-purple-600", label: "Search" },
  ListDir: { bg: "bg-emerald-50", text: "text-emerald-600", label: "ListDir" },
  list_directory: { bg: "bg-emerald-50", text: "text-emerald-600", label: "ListDir" },
  list_dir: { bg: "bg-emerald-50", text: "text-emerald-600", label: "ListDir" },
  WebFetch: { bg: "bg-cyan-50", text: "text-cyan-600", label: "Web" },
  web_search: { bg: "bg-cyan-50", text: "text-cyan-600", label: "Web" },
  WebSearch: { bg: "bg-cyan-50", text: "text-cyan-600", label: "Web" },
  Task: { bg: "bg-violet-50", text: "text-violet-600", label: "Task" },
  TaskCreate: { bg: "bg-violet-50", text: "text-violet-600", label: "Task" },
  TaskUpdate: { bg: "bg-violet-50", text: "text-violet-600", label: "Task" },
  TaskList: { bg: "bg-violet-50", text: "text-violet-600", label: "Task" },
  TaskGet: { bg: "bg-violet-50", text: "text-violet-600", label: "Task" },
};

export const DEFAULT_BADGE = { bg: "bg-gray-50", text: "text-gray-500", label: "" };
